export function elements() {
return {

    contract: {
        detailsPage: "https://core.service-app.com/delivery/contract-detail/client/10001/contract/2706/overview",
        header: "div.header-wrapper h1"
    },

    editTicket: {
        tabButton: "fieldflow-tab:nth-child(2) button",
        tabHeader: "div.title-content h3",
        searchInput: "input[placeholder='Search']",
        row: "tbody tr",
        link: "td[headers='table-header-0-2-1'] a",
        detailsHeader: "div.header-wrapper h1"
    },  

    ticketFinancials: {
        totalPrice: "app-detail-node[title='Total Price'] div",
        totalAuthCost: "app-detail-node[title='Total Authorized Cost'] div",
        totalPriceHeader: ":nth-child(1) > [headers='table-header-0-8-1']",
        totalAuthCostHeader: ":nth-child(1) > [headers='table-header-0-9-1']",
        marginHeader: ":nth-child(1) > [headers='table-header-0-10-1']",
        ticketsListUrl: "https://core.service-app.com/delivery/contract-detail/client/10001/contract/2706/tickets"
    },

    spinnerLoading: "mat-spinner[role='progressbar'] div.mdc-circular-progress__circle-clipper.mdc-circular-progress__circle-right svg circle",
    taskDashboardHeader: "div.header-wrapper h1",
    taskDashboardHeaderSelector: "div.header-wrapper h1",
    activitiesTabButton: "button",
    addActivityButton: "button",
    modalContainer: ".cds--modal-container.cds--modal-container--lg",
    modalHeader: ".cds--modal-header.default",
    activityInput: "input[placeholder='Activity Name...']",
    activityRow: "td[title='Automation Test Activity']",
    activityCheckbox: "input[type='checkbox']",
    activitySaveButton: ".buttons > .cds--btn--primary",
    activitySuccessMessage: "div[aria-label='Saved Successfully']",
    successImageSelector: "img[src='assets/images/D1.png']",
    
    schedulesTabButton: ":nth-child(6) > button > p",
    addScheduleButton: "button.primary",
    scheduleModalContainer: "fieldflow-dialog",
    scheduleModalHeader: ".header div",
    calendarOpenButton: "button[aria-label='Open calendar']",
    calendarNextButton: ".mat-calendar-next-button",
    calendarCellSelector: ".mat-calendar-body-cell-content",
    timePickerButton: ".open-time-picker--button > .mat-icon",
    scheduleSaveButton: ".actions > :nth-child(2) > .primary",
    scheduleSuccessMessage: "div[aria-label='Ticket Schedule is successfully added.']",
    updateScheduleSuccessMessage: "div[aria-label='Schedule is successfully updated!']",
    editScheduleButton: "[buttonstyle='primary'] > button > .mat-icon",
    editScheduleModalHeader: ".header div",
    datePickerInput: "input[formcontrolname='publishedSchedule']",
    monthYearButton: "button[aria-label='Choose month and year']",
    selectYear2025: ".owl-dt-year-2025 > .owl-dt-calendar-cell-content",
    selectMonthNovember: ".owl-dt-month-11 > .owl-dt-calendar-cell-content",
    selectDayDecember30: "td[aria-label='December 30, 2025'] span[class='owl-dt-calendar-cell-content']",
    timePickerContainer: "owl-date-time-container",
    hourInput: "fieldflow-time-picker[formcontrolname='clientReqTime'] input",
    publishHourInput: "owl-date-time-timer-box:nth-child(1) input",
    minuteInput: "owl-date-time-timer-box:nth-child(2) input",
    confirmDateTimeButton: ".owl-dt-container-buttons > :nth-child(2) > .owl-dt-control-content",

    sitesTabButton: "button:contains('Sites')",
    siteInfoHeader: "h3",
    endClientDropdown: ".ng-value-container",
    addLocationButton: "button:contains('Add Location')",
    siteModalContainer: ".cds--modal-container.cds--modal-container--lg",
    siteModalHeader: ".cds--modal-header.default",
    searchInput: "input[placeholder='Search...']",
    radioButton: ".cds--radio-button__appearance",
    saveClientSiteButton: "button:contains('Save Client Site')",
    siteSuccessMessage: "div[aria-label='Site updated']",

    ticketsTabButton: "fieldflow-tab:nth-child(2) button",
    uploadsTabButton: "fieldflow-tab:nth-child(8) button",
    bulkUploadButton: "fieldflow-button button.primary",
    bulkTicketHeader: "div.header div",
    uploadFileButton: ".btn-upload-file",
    bulkUploadName: ".content > .mat-mdc-form-field > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix",
    ticketsHeader: "div.title-content h3",
    addTicketButton: "button:contains('Add Ticket')",
    addTicketModal: "fieldflow-dialog",
    ticketTitleLabel: "mat-label",
    ticketTitleInput: "input[placeholder='Ticket Title']",
    ticketSaveButton: "div.actions button.primary.ng-star-inserted",
    ticketSuccessMessage: "div[aria-label='Saved Successfully']",
    ticketEmailLabel: "div.no-email-selected h3",
    ticketUploadSuccessMessage: "div[aria-label='Uploaded Successfully']",
    ticketUploadSuccess: "tbody > :nth-child(1) > :nth-child(6)",

    buyTabIcon: ".mat-icon",
    buyTabText: "shopping_cart",
    stagedLabel: "app-legacy-status-label",
    editPoIcon: "tbody tr:first-child mat-icon",
    modalContainerLg: ".cds--modal-container.cds--modal-container--lg",
    modalHeaderPo: "h4.card-title",

    poScope: {
        tabButton: "button",
        header: "h3",
        toggle: ".cds--toggle__switch",
        scheduleDropdown: "select[formcontrolname='ticketScheduleId']",
        dropdownOption: "select[formcontrolname='ticketScheduleId'] option",
        textEditor: ".ql-editor",
        saveButton: "button.cds--btn.cds--btn--primary",
        successMessage: "div[aria-label='Success']"
    },

    poTabButton: "#n-tab-1-header",
    poActivityRow: "body > app-root > app-loading-handler > app-site-layout > fieldflow-primary-layout > div > div > div > app-ticket-detail > app-loading-handler > div > div > app-buy-tickets > ibm-placeholder > app-po-modal > ibm-modal > cds-overlay > section > div > div > ibm-table-container > ibm-tabs > ibm-tab > div > app-po-activities > div > div > table > tbody > tr > td:nth-child(2)",
    poActivityCheckbox: "input[type='checkbox']",
    poCostInput: ":nth-child(7) > .ng-untouched",
    poActivitySaveButton: ":nth-child(2) > .primary",
    poActivitySuccessToast: "div[aria-label='Success']",

    deliverablesTab: "button",
    deliverablesHeader: "h1",
    addDeliverableButton: "button.bx--btn--primary",
    addDeliverableModalHeader: "h3", 
    deliverableNameInput: "input[formcontrolname='name']",
    deliverableTypeDropdown: "ng-select[formcontrolname='deliverableTypeId']",
    deliverableTypeOption: ".ng-dropdown-panel .ng-option",
    noOfFilesInput: "input[formcontrolname='noOfFiles']",
    deliverableSaveButton: "button", 
    deliverableAddedToast: "div[aria-label='Deliverable requirement added successfully']",
    deliverableUploadButton: "button",
    deliverableUploadModalHeader: "div",
    deliverableFileInput: "input[type='file']",
    uploadFileInput: "input[type='file'][formcontrolname='ticketFile'][name='ClientFile']",
    deliverableNextButton: "button.primary",
    deliverableFinalSaveButton: "button.primary",
    deliverableFinalToast: "div[aria-label='Deliverables are successfully added.']",

    poAssignTech: {
        techpoTabButton: "button[id^='n-tab-'][role='tab']",
        poPageHeader: "h1",
        createTechAssignmentButton: "fieldflow-button[routerlink='assign-technician'] button.primary",
        assignTechHeader: "h1",
        techRadioButton: "cds-radio input[type='radio']",
        finalizeAssignmentButton: "fieldflow-button button.primary",
        successAssignMessage: "div[aria-label='Successfully assigned technician to purchase order']",
        technicianAssignedSection: "h4",
        breadcrumbToPo: "lib-breadcrumb-item a",
        mtRadioSwitch: ".mdc-switch",
        addPoHeader: "h3"
    },

    reviewsTabButton: "button",
    ratingsHeader: "div.title-content h3",
    newRatingButton: "button",
    ratingModal: "fieldflow-dialog.ng-untouched.ng-pristine.ng-invalid",
    ratingModalHeader: "div.header div",
    reviewerDropdown: "ng-select[formcontrolname='reviewerId']",
    technicianRatingDropdown: "ng-select[formcontrolname='technicianId']", 
    ratingRadio1: "#mat-radio-2 > .mdc-form-field > .mdc-label",
    ratingRadio2: "#mat-radio-5 > .mdc-form-field > .mdc-label",
    ratingRadio3: "#mat-radio-8 > .mdc-form-field > .mdc-label",
    ratingRadio4: "#mat-radio-11 > .mdc-form-field > .mdc-label",
    starRating: ".br-unit",
    saveRatingButton: "button",
    ratingSuccessMessage: "div[aria-label='Rating saved successfully']",

    clientsTabIcon: "mat-icon",
    clientsPageHeader: "h1",
    addClientsButton: "button",
    addClientPageHeader: "h1",
    clientNameInput: "input[placeholder='Client Name']",
    clientRelationshipDropdown: "select[id='select-0']", 
    clientCurrencyInput: ".ng-select-multiple > .ng-select-container > .ng-value-container > .ng-input > input",
    clientCountryDropdown: "#select-1",
    clientSaveButton: "button",
    clientSuccessMessage: "div[aria-label='Uploading client...']",

    addVendorHeader: "div.title-content h3",
    vendorNameInput: "#name",
    vendorTypeDropdown: "select[formcontrolname='vendorType']",
    vendorEmailField: "input[placeholder='Vendor Email']", 
    vendorStateProvinceField: "input[placeholder='State/Province']",
    vendorCountryDropdown: "select[formcontrolname='countryId']",
    vendorBusinessPhoneField: "input[placeholder='Business Phone']",
    vendorZipPostalCodeField: "input[placeholder='ZIP/Postal Code']",
    vendorAddressField: "input[placeholder='Address']",
    vendorCityField: "input[placeholder='City']",
    vendorWebsiteField: "input[placeholder='Website']",
    vendorTaxIdField: "input[placeholder='Tax ID']",
    vendorSaveButton: ".buttons > .cds--btn--primary",
    vendorSuccessMessage: "div[aria-label='Vendor created successfully!']",
    vendorSearchField: "input[placeholder='Search Name...']",
    vendorTableRow: "tbody tr",
    editVendorButton: ".mat-icon.notranslate.material-symbols-outlined.primary.mat-icon-no-color",
    editVendorPageHeader: ".header-wrapper h1",
    editVendorNameInput: "#mat-input-20",
    vendorPaymentTypeDropdown: "select[formcontrolname='paymentTypeId']",
    vendorPaymentTermsDropdown: "select[formcontrolname='paymentTermId']",
    vendorCurrencyInput: "mat-form-field select[formcontrolname='currencyId']",
    vendorEditButton: "tbody tr:nth-child(1) td:nth-child(17) fieldflow-icon-button:nth-child(1) button:nth-child(1) mat-icon:nth-child(1)",
    vendorEditSuccessMessage: "div[aria-label='Updated Successfully']",
    vendorDeleteSuccessMessage: "div[aria-label='Deleted successfully']",

    clientSearchField: "input[placeholder='Search Name...']", 
    clientTable: "table[cdstable].cds--data-table", 
    editClientButton: "mat-icon",
    editClientPageHeader: "h1",
    clientNameField: "input[placeholder='Client Name']",
    clientFileUploadInput: "input[type='file']", 
    clientPhoneField: "input[placeholder='Phone']", 
    clientEmailField: "input[placeholder='Email']",
    clientAddressField: "input[placeholder='Address']",
    clientCityField: "input[placeholder='City']",
    clientStateField: "input[placeholder='State']",
    clientPostalCodeField: "input[placeholder='Postal Code']",
    editClientSuccessMessage: "div[aria-label='Update Successfully!']",

    deleteButton: "button.danger",
    confirmDeleteButton: "button.danger",
    deleteSuccessMessage: "div[aria-label='Deleted Successfully']",
    noRecordsMessage: "div.nodata.ng-star-inserted",

    clientTitle: "span[class='name']",
    editLocationButton: "td button mat-icon[role='img'].mat-icon.notranslate.material-symbols-outlined.primary.mat-icon-no-color",
    deleteLocationButton: "[buttonstyle='danger'] > button > .mat-icon",
    deleteConfirmButton: ".cds--btn--danger",
    locationNameInput: "input[placeholder='Location Name']",
    phoneInput: "input[placeholder='Phone']",
    addressInput: "ng-select[placeholder='Select Address'] input",
    addressDropdown: "div.ng-option",
    locationStateInputOld: "ng-select[placeholder='State'] input[role='combobox']",
    locationStateInput: "ng-select[formcontrolname='state'] input",
    locationNameHeader: "table td[title='Cypress Test Location']",
    locationAddressHeader: "table td[title='2050 East Charleston Boulevard']",
    locationCityHeader: "table td[title='Las Vegas']",
    locationStateCountryHeader: "table td[title='NV, United States']",
    locationZipHeader: "table td[title='89104']",
    
    clientPortal: {
        addDocumentButton: "Add Document",
        addLocationButton: "a[href='/Location/Add']",
        addNewDocumentLabel: "Add New Document",
        addTechnicianButton: "button.btn.btn-default.btn-block",
        attachedDocumentsLabel: "Attached Documents",
        contractDropdown: "mat-select[formcontrolname='Contract']",
        contractOption: "mat-option",
        countryDropdown: "ng-select[bindlabel='text'][bindvalue='id']",
        dashboard: "a[routerlink='/Dashboard']",
        datePickerCancel: "button.owl-dt-control-button",
        docDropdownOption: ".ng-option",
        docSaveButton: ".mat-raised-button.mat-primary",
        documentDescription: "Test Cypress Description",
        documentDescriptionInput: "textarea[formcontrolname='Description']",
        documentTitle: "CP Document Test",
        documentTitleInput: "input[placeholder='Document Title']",
        documentTypeDropdown: "ng-select[formcontrolname='DocumentType']",
        documentTypeOption: "Other",
        dropdownOption: ".ng-dropdown-panel .ng-option",
        endClientDropdown: "ng-select[bindlabel='text'][bindvalue='id']",
        fileToUpload: "TestDocAttachment.docx",
        fileUploadInput: "input[type='file']",
        issueDescription: "input[formcontrolname='Issue']",
        locationAddressInput: "input[role='combobox'][aria-placeholder='Type Address']",
        locationDropdown: "ng-select[bindlabel='text'][bindvalue='id']",
        locations: "li[routerlink='/Location/Manage'] a",
        myTicketsLink: ".tickets > a",
        numTechniciansDropdown: "ng-select[placeholder='Select No Of Technicians']",
        requiredTools: "textarea[formcontrolname='TicketRequiredTools']",
        responseDateInput: "input[formcontrolname='requestedResponseDate']",
        saveButton: "button.btn.btn-info.btn-sm",
        saveButtonLabel: "Save",
        scopeOfWork: "textarea[formcontrolname='ScopeOfWork']",
        specialConditions: "textarea[formcontrolname='SpecialConditions']",
        specialRequirements: "textarea[formcontrolname='SpecialRequirements']",
        successMessage: "div[aria-label='Success']",
        technicianLevelDropdown: "ng-select[placeholder='Select Technical Level']",
        ticketProblemDropdown: "mat-select[formcontrolname='TicketProblemCode']",
        ticketProblemOption: "mat-option"
    },

    vendorRates: {
        vendorUrlProfile: "https://core.service-app.com/vendors/vendor-details/300762/profile",
        countryDropdown: "input[formcontrolname='countryId'][placeholder='Select Country']",
        unitedStates: "#mat-option-251",
        currencyDropdown: "input[formcontrolname='currencyId']",
        ratesUsd: "#mat-option-417",
        hoursOfBaseRate: "input[formcontrolname='requiredHoursOfBaseRate']",
        standardHourlyRate: "input[formcontrolname='standardHourly']",
        standardBaseHourlyRate: "input[formcontrolname='standardBaseHourly']",
        standardAdditionalHoursRate: "input[formcontrolname='standardAdditionalHoursRate']",
        toastMessageContainer: "#toast-container > .ng-trigger",
        comments: "textarea[formcontrolname='paymentComments']"
    },
    techUrlProfile: "https://core.service-app.com/technicians",

    bcSync: {
        ticketSync: ".normal > .mat-icon",
        ticketPartialSync: ".warning > .mat-icon",
        activityPoSync: ".badge.bc-synced",
        searchPageSync: "tbody tr:nth-child(1) td:nth-child(1) app-bc-badge:nth-child(1) div:nth-child(1) span:nth-child(1)"
    },

    toastMsg: {
        autoUpdate: ".toast-info > .toast-message"
    },

    deals: {
        opportunitiesTabIcon: "mat-icon", 
        dealPageHeader: ".custom-h1",
        addDealButton: "button", 
        addDealHeader: ".card-title",
        modalContainer: "div.cds--modal-container[role='dialog']",
        dealNameLabel: "#cds-label-0",
        dealNameInput: "[formcontrolname='dealName']",
        scheduleDateInput: "#datepicker-1-input",
        priorityDropdown: "ng-select[formcontrolname='priorityId']",
        priorityOption: ".ng-dropdown-panel .ng-option",
        dealTypeDropdown: "ng-select[formcontrolname='dealType']",
        dealTypeOption: ".ng-dropdown-panel .ng-option",
        descriptionTextarea: "textarea[formcontrolname='description']",
        solutioningOwnerDropdown: "ng-select[formcontrolname='solutioningOwnerId']",
        solutioningOwnerInput: "ng-select[formcontrolname='solutioningOwnerId'] input[type='text']",
        solutioningOwner: ".ng-option",
        salesOwnerDropdown: "ng-select[formcontrolname='salesOwnerId']",
        salesOwnerInput: "ng-select[formcontrolname='salesOwnerId'] input[type='text']",
        clientDropdown: "ng-select[formcontrolname='clientId']",
        clientInput: "ng-select[formcontrolname='clientId'] input[type='text']",
        firstNameInput: "input[formcontrolname='firstName']",
        lastNameInput: "input[formcontrolname='lastName']",
        emailInput: "input[formcontrolname='email']",
        primaryContactPhoneInput: "input[formcontrolname='primaryContactPhoneNo']",
        clientPhoneInput: "input[formcontrolname='clientPhoneNo']",
        addressInput: "input[formcontrolname='address']",
        saveButton: "button.primary",
        spinnerImage: ".spinner-image",
        dealsPageUrl: "https://core.service-app.com/sales/deal",
        dealSearchInput: "#search-0",
        deleteDealButton: ".delete-btn > button > .mat-icon",
        confirmDeleteButton: "mat-dialog-container .actions button.danger",
        dealDeletionSuccessMessage: "Deal deleted successfully."
    },
    teams: {
        teamManagementPage: "https://core.service-app.com/general/settings/manage-teams",
        addTeamButton: ".primary.ng-star-inserted",
        editTeamButton: ".mat-icon.notranslate.material-symbols-outlined.primary.mat-icon-no-color",
        teamNameInput: "input[placeholder='(e.g Sales Team)']",
        teamEmailInput: "input[placeholder='(e.g vendorsupport@example.com)']",
        teamMemberCombobox: "input[role='combobox']",
        teamLeadDropdown: "#select-0",
        teamMemberDropdown: ":nth-child(2) > .ng-select-searchable > .ng-select-container",
        searchTeamInput: "input[placeholder='Search Name...']",
        teamTitleCell: "[headers='table-header-0-0-1']",
        teamEmailCell: "[headers='table-header-0-3-1']",
        editIcon: ".mat-icon.notranslate.material-symbols-outlined.primary.mat-icon-no-color",
        updateButton: ".bx--col > .cds--btn--primary",
        deleteIcon: ".mat-icon.notranslate.material-symbols-outlined.danger.mat-icon-no-color",
        deleteButton: ".cds--btn.cds--btn--danger",
        cancelButton: ".mx-3",
        saveButton: "button[type='submit']"
    },

    contractDocument: {
        contractDocumentsPage: "https://core.service-app.com/delivery/contract-detail/client/10001/contract/2706/documents",
        pageHeader: ".title-content > h3",
        addDocumentButton: ".primary.ng-star-inserted",
        modalContainer: ".cds--modal.cds--modal-tall.is-visible",
        modalHeader: ".cds--modal-header__heading",
        documentNameInput: "#cds-label-0",
        documentTypeDropdown: "body > app-root:nth-child(1) > app-loading-handler:nth-child(1) > app-site-layout:nth-child(3) > fieldflow-primary-layout:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > app-contract-detail:nth-child(2) > div:nth-child(2) > app-contract-documents:nth-child(2) > ibm-modal:nth-child(1) > cds-overlay:nth-child(1) > section:nth-child(1) > div:nth-child(1) > section:nth-child(2) > form:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ibm-select:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > select:nth-child(1)",
        descriptionTextarea: ".outside > .cds--text-input",
        saveButton: ".cds--modal-footer > .cds--btn--primary"
    },

    taskManager: {
        sidebarHoverTab: "div.tab.ng-star-inserted",
        pinButton: "app-sidebar-header button:nth-child(2) mat-icon:nth-child(1)"
    },

    tasksUpdate: {
        ticketAccordion: "app-accordion-row button.title-wrapper",
        toBeScheduledText: "app-accordion-row.ng-tns-c84663556-20 > .ng-trigger-contentVisibility > :nth-child(2) > .wrapper > .content > p",
        pendingDeliverablesText: "app-accordion-row.ng-tns-c84663556-52 > .ng-trigger-contentVisibility > :nth-child(2) > .wrapper > .content > p",
        finalAccordion: "app-accordion-row button.title-wrapper",
        finalTaskInternalSource: "[style='padding: 12px;'] > :nth-child(2) > .wrapper > app-task-actions > [style='background-color: #2ecc71;'] > .mat-icon",
        finalTaskSubmitInvoice: "[style='padding: 12px;'] > :nth-child(3) > .wrapper > app-task-actions > [style='background-color: #2ecc71;'] > .mat-icon",
        finalTaskConfirmReceipt: "[style='padding: 12px;'] > :nth-child(4) > .wrapper > app-task-actions > [style='background-color: #2ecc71;'] > .mat-icon",
        ticketStatusLabel: ".primary > app-legacy-status-label",
        taskStatusPill: "app-legacy-status-label:contains('Client Complete')",
        ticketListStatusCell: ":nth-child(1) > [headers='table-header-0-4-1'] > .ng-star-inserted"
    }
}

  };
